<p>
    <?php
    _e(
        '"The Pool" refers to the pool of posts and pages that are candidates for display as related to the current entry.',
        'yarpp'
    )
    ?>
</p>

<?php
    foreach ($yarpp->get_taxonomies() as $taxonomy) {
        $this->exclude($taxonomy->name, sprintf(__('Disallow by %s:', 'yarpp'), ucwords($taxonomy->labels->name)), $taxonomy->_builtin);
    }

    $this->checkbox('show_pass_post', __('Display password protected posts', 'yarpp'));

    $recent = yarpp_get_option('recent');
    if ((bool) $recent) {
        list($recent_number, $recent_units) = explode(' ', $recent);
    } else {
        $recent_number = 12;
        $recent_units = 'month';
    }

    $recent_number = '<input name="recent_number" type="text" id="recent_number" value="'.esc_attr($recent_number).'" size="2" />';

    $recent_units  =
    '<select name="recent_units" id="recent_units" style="vertical-align:inherit">'.
        '<option value="day" '  .(($recent_units === 'day')   ? 'selected' : null).'>'.__('day(s)', 'yarpp').'</option>'.
        '<option value="week" ' .(($recent_units === 'week')  ? 'selected' : null).'>'.__('week(s)', 'yarpp').'</option>'.
        '<option value="month" '.(($recent_units === 'month') ? 'selected' : null).'>'.__('month(s)', 'yarpp').'</option>'.
    '</select>';
?>

<div class='yarpp_form_row yarpp_form_checkbox'>
    <div>
        <input type='checkbox' name='recent_only' id='yarpp-recent_only' value='true' <?php checked((bool) $recent) ?> />
				<label for="yarpp-recent_only">
        <?php 
				
				printf(
        // translators: 1: HTML for a number field, 2: HTML for a units dropdown (eg "week(s)", "day(s)", month(s))
        __('Display only posts from the past %1$s %2$s', 'yarpp'),
        $recent_number,
        $recent_units
				);
        ?>
				</label>
    </div>
</div>

<?php
	$this->checkbox( 'past_only', __( "Display only posts older than current post", 'yarpp' )." <span class='yarpp_help dashicons dashicons-editor-help' data-help='" . esc_attr( __( "Only posts older than the current post will be displayed.", 'yarpp' ) ) . "'>&nbsp;</span>" );

	$this->checkbox( 'cross_relate', __( "Display results from all post types", 'yarpp' )." <span class='yarpp_help dashicons dashicons-editor-help' data-help='" . esc_attr( __( "When disabled, only other posts with the same post type will be displayed. For example, only posts will be displayed as related to a post, only pages will be displayed as related to a page, etc.", 'yarpp' ) ) . "'>&nbsp;</span>" );
?>
